# App
spring.application.name=portfolio-backend
server.port=8080

# MongoDB ? local
=mongodb://localhost:27017/portfoliodb

# JWT secret (keep this private ? minimum 32 characters)
jwt.secret=portfolio_secret_key_minimum_32_chars_long
jwt.expiration=86400000

# CORS allowed origin
cors.allowed-origin=http://localhost:5173



#


server.port=${PORT:8080}
spring.data.mongodb.uri=${spring.data.mongodb.uri:mongodb+srv://portfolioUser:Chavan@123@cluster0.wfs4stz.mongodb.net/?appName=Cluster0}
cors.allowed-origin=${CORS_ORIGIN:http://localhost:5173}
spring.application.name=portfolio-backend