

### JWT secret (keep this private ? minimum 32 characters)
#jwt.secret=portfolio_secret_key_minimum_32_chars_long






#


server.port=${PORT:8080}
spring.data.mongodb.uri=${spring.data.mongodb.uri:mongodb+srv://portfolioUser:Chavan%40123@cluster0.wfs4stz.mongodb.net/?appName=Cluster0}
cors.allowed-origin=${CORS_ORIGIN:http://localhost:5173}
jwt.secret=${Jwt.secret=portfolio_secret_key_minimum_32_chars_long}
jwt.expiration=86400000
spring.application.name=portfolio-backend