# App
spring.application.name=portfolio-backend
server.port=8080

# MongoDB ? local
spring.data.mongodb.uri=mongodb+srv://chavanprathamesh813_db_user:0CrHGrUD8jVe4vQJ@cluster0.uif3moy.mongodb.net/portfolioNew?appName=Cluster0

# JWT secret (keep this private ? minimum 32 characters)
jwt.secret=portfolio_secret_key_minimum_32_chars_long
jwt.expiration=86400000

# CORS allowed origin
cors.allowed-origin=http://localhost:5173,https://portfolio-frontend-react-blond.vercel.app



#mongodb+srv://portfolioUser:Chavan@123@cluster0.wfs4stz.mongodb.net/?appName=Cluster0

